version: "3.9"
services:
    app:
        container_name: receitas
        image: receitas
        volumes:
            - .:/app
            - /app/node_modules
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - "5173:5173"
